# Generated by Django 3.1.7 on 2021-07-01 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'campaigns',
            },
        ),
        migrations.CreateModel(
            name='CampaignPerDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('reach', models.IntegerField(null=True)),
                ('spend', models.IntegerField(null=True)),
                ('clicks', models.IntegerField(null=True)),
                ('impressions', models.IntegerField(null=True)),
                ('installs', models.IntegerField(null=True)),
                ('views', models.IntegerField(null=True)),
                ('ctr', models.IntegerField(null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
            ],
            options={
                'db_table': 'campaign_per_dates',
            },
        ),
    ]
